### ISSUE TITLE
WeakCallbackGroupsToGuardConditionsMap

### ISSUE THREAD

**Issue by RobotBramhana** [irobot-ros/events-executor#11]
Greetings,
I was going through the code implementation and found that ```WeakCallbackGroupsToGuardConditionsMap``` has not been added in the ```events_executor_entities_collector``` which contrarily is present in ```rclcpp::Executor``` [here](https://github.com/ros2/rclcpp/blob/37adc03c11171f67c213ee72f7ce43fdcbda7b9e/rclcpp/include/rclcpp/executor.hpp#L569). This curiosity whirled up in my mind but to find an answer on my own in vain. Please be kind to let me know whether there were any design considerations not to add this data structure that could have had any other adverse effects on the performance or anything as such.

**Comment by alsora** [comment]
Hi @RobotBramhana, there are no designs considerations behind it.
The changes you mention are relatively recent and we haven't included them here yet.

Feel free to open a PR

**Comment by alsora** [comment]
Hi @RobotBramhana, we just applied the fixes to the events-executor.
See https://github.com/irobot-ros/events-executor/pull/14
