### ISSUE TITLE
The performance is not as good as expected

### ISSUE THREAD

**Issue by 282902479** [irobot-ros/events-executor#5]
Hello, I only modified the rclcpp layer, and added this project to my project. I tested the performance comparison standard executor through the ros2 performance tool. Test cases: many to many pubs, sub statistics of latency, CPU, but the results were at most the same as StaticSingleThreadExecutor，not better than it

**Comment by alsora** [comment]
Hi, without more details on what you did and how you measured performance there isnt much I can help with.

Adding this project to your workspace is not sufficient to get an improvement, you also need to modify your application to use the new executor.

**Comment by 282902479** [comment]
> Hi, without more details on what you did and how you measured performance there isnt much I can help with.
> 
> Adding this project to your workspace is not sufficient to get an improvement, you also need to modify your application to use the new executor.

Enabling Intra-Process Optimization in rclcpp can result in [a runtime exception](https://github.com/ros2/rclcpp/blob/rolling/rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp#L90).When will this bug be fixed? Or is there any relevant submission?

**Comment by 282902479** [comment]
> 是的，这是在当前已知的错误和限制中列出的。 https://github.com/irobot-ros/events-executor#known-bugs-and-limitations
> 
> 但是，我看不出这与您的第一个问题有什么关系。

I put the header file under the project in ros2 rclcpp/include, and the source file in rclcpp src. The compilation is successful. Using the ros2-performance tool, modify the source code to adapt to events executor and test the performance. The results are as I wrote above

![image](https://user-images.githubusercontent.com/50130211/204313509-0efa9e07-0b21-4480-8564-bffaf9fbb9fd.png)


The command is as follows：
$ ros2 run performance_test_examples json_system_main --executor 3 --monitor_stats 1 --use_ipc 1 --duration 300 --json /path/ros2-performance/irobot_benchmark/topology/sierra_nevada.json

**Comment by 282902479** [comment]
> > 是的，这是在当前已知的错误和限制中列出的。 https://github.com/irobot-ros/events-executor#known-bugs-and-limitations
> > 但是，我看不出这与您的第一个问题有什么关系。
> 
> I put the header file under the project in ros2 rclcpp/include, and the source file in rclcpp src. The compilation is successful. Using the ros2-performance tool, modify the source code to adapt to events executor and test the performance. The results are as I wrote above
> 
> ![image](https://user-images.githubusercontent.com/50130211/204313509-0efa9e07-0b21-4480-8564-bffaf9fbb9fd.png)
> 
> The command is as follows： $ ros2 run performance_test_examples json_system_main --executor 3 --monitor_stats 1 --use_ipc 1 --duration 300 --json /path/ros2-performance/irobot_benchmark/topology/sierra_nevada.json



> > 是的，这是在当前已知的错误和限制中列出的。 https://github.com/irobot-ros/events-executor#known-bugs-and-limitations
> > 但是，我看不出这与您的第一个问题有什么关系。
> 
> I put the header file under the project in ros2 rclcpp/include, and the source file in rclcpp src. The compilation is successful. Using the ros2-performance tool, modify the source code to adapt to events executor and test the performance. The results are as I wrote above
> 
> ![image](https://user-images.githubusercontent.com/50130211/204313509-0efa9e07-0b21-4480-8564-bffaf9fbb9fd.png)
> 
> The command is as follows： $ ros2 run performance_test_examples json_system_main --executor 3 --monitor_stats 1 --use_ipc 1 --duration 300 --json /path/ros2-performance/irobot_benchmark/topology/sierra_nevada.json

I now follow readme.txt put irobot_ events_executor in my ros2_humble As a component, it is tested using the humble-event-executor branch of ros2-performance. Every time you specify the use of cyclonedds middleware, the results are the same, not better than static single

**Comment by alsora** [comment]
can you share the log files from this last execution?

**Comment by 282902479** [comment]
> can you share the log files from these last executions? you should have a directory of logs from each execution, we need the one with the static single threaded executor and the one with the events executor.

[static_log.zip](https://github.com/irobot-ros/events-executor/files/10121773/static_log.zip)
[event_log.zip](https://github.com/irobot-ros/events-executor/files/10121776/event_log.zip)

**Comment by 282902479** [comment]
> > can you share the log files from these last executions? you should have a directory of logs from each execution, we need the one with the static single threaded executor and the one with the events executor.
> 
> [static_log.zip](https://github.com/irobot-ros/events-executor/files/10121773/static_log.zip) [event_log.zip](https://github.com/irobot-ros/events-executor/files/10121776/event_log.zip)

In addition to performance, I also want to know whether the bug（Enabling Intra-Process Optimization in rclcpp can result in [a runtime exception](https://github.com/ros2/rclcpp/blob/rolling/rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp#L90).） has been located and when it can be fixed

**Comment by 282902479** [comment]
> can you share the log files from these last executions? you should have a directory of logs from each execution, we need the one with the static single threaded executor and the one with the events executor.

I look forward to your reply

**Comment by alsora** [comment]
Hi,

 - I updated the instructions; these now include details on how to fix the issue with intra-process communication.
 
 - I tested the executor using multiple topologies and the events executor always uses less CPU (approximately 1/3) of both the `SingleThreadedExecutor` and the `StaticSingleThreadedExecutor`.
 
 Please, carefully follow the instructions and make sure that you are using the correct libraries.

**Comment by 282902479** [comment]
> 你好，
> 
> * 我更新了说明；这些现在包括有关如何解决进程内通信问题的详细信息。
> * 我使用多个拓扑测试了执行程序，事件执行程序总是使用较少的 CPU（大约 1/3），两者都是`SingleThreadedExecutor`和`StaticSingleThreadedExecutor`.
> 
> 请仔细按照说明进行操作，并确保您使用的是正确的库。
> 
> 如果您正在评估性能，请确保您正在构建启用了优化的工作区。 对于事件执行器，这还需要修改 rclcpp 库。 在此处查看详细信息https://github.com/irobot-ros/events-executor#known-bugs-and-limitations

Could you please tell me about the relevant branches of events-executor and ros2-performance you use?
