### ISSUE TITLE
Update docs?

### ISSUE THREAD

**Issue by andre-nguyen** [irobot-ros/events-executor#6]
Hi

The readme mentions that

https://github.com/irobot-ros/events-executor/blob/6f4343fc1e7d7719cabe0f14059c897b9698cf5a/README.md?plain=1#L27

Now that https://github.com/ros2/rmw_fastrtps/pull/619 is merged in, is this not an issue anymore?

**Comment by alsora** [comment]
Yes! Thanks for pointing it out.
I will update the docs accordingly.

**Comment by alsora** [comment]
Hi, we just updated the instructions in the README!
https://github.com/irobot-ros/events-executor

I'm closing this issue
